version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Alebo port, ktorý tvoja aplikácia používa
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/moja_databaza # URL MongoDB
    command: npm start

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Port MongoDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
